"""hilangin Unix

Revision ID: 27f0d8933b63
Revises: cbcf36ca7352
Create Date: 2019-03-18 22:13:41.490441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f0d8933b63'
down_revision = 'cbcf36ca7352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('country_code_key', 'country', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('country_code_key', 'country', ['code'])
    # ### end Alembic commands ###
