"""deskripsi

Revision ID: 35be7d29ec32
Revises: 380a69bf7421
Create Date: 2019-03-19 18:16:36.250741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35be7d29ec32'
down_revision = '380a69bf7421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deskripsi', sa.Column('deskripsi', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deskripsi', 'deskripsi')
    # ### end Alembic commands ###
