"""tambah file

Revision ID: 3b619fd16b25
Revises: a32c0978b43b
Create Date: 2019-03-25 22:25:44.817525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b619fd16b25'
down_revision = 'a32c0978b43b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('file', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'file')
    # ### end Alembic commands ###
