"""gen slug

Revision ID: 457f403641e6
Revises: 4a5d036b91cb
Create Date: 2019-03-22 22:45:47.809641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457f403641e6'
down_revision = '4a5d036b91cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Layanan', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'Layanan', ['slug'])
    op.add_column('Products', sa.Column('slug', sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, 'Products', ['slug'])
    op.drop_constraint('kontak_name_key', 'kontak', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('kontak_name_key', 'kontak', ['name'])
    op.drop_constraint(None, 'Products', type_='unique')
    op.drop_column('Products', 'slug')
    op.drop_constraint(None, 'Layanan', type_='unique')
    op.drop_column('Layanan', 'slug')
    # ### end Alembic commands ###
