"""adding social media

Revision ID: 4a5d036b91cb
Revises: 35be7d29ec32
Create Date: 2019-03-22 17:04:36.756181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a5d036b91cb'
down_revision = '35be7d29ec32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Deskripsi', sa.Column('sm_fb', sa.String(length=64), nullable=True))
    op.add_column('Deskripsi', sa.Column('sm_ig', sa.String(length=64), nullable=True))
    op.add_column('Deskripsi', sa.Column('sm_wa', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Deskripsi', 'sm_wa')
    op.drop_column('Deskripsi', 'sm_ig')
    op.drop_column('Deskripsi', 'sm_fb')
    # ### end Alembic commands ###
