"""Products

Revision ID: 552f41c54763
Revises: 74a59d32523c
Create Date: 2019-03-28 20:50:59.360534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552f41c54763'
down_revision = '74a59d32523c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('slug', sa.String(length=100), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('filename_images', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('kategori_id', sa.Integer(), nullable=True),
    sa.Column('file_filename', sa.String(length=500), nullable=True),
    sa.Column('file', sa.LargeBinary(length=16000000), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['kategori.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename_images'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_Products_timestamp'), 'Products', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Products_timestamp'), table_name='Products')
    op.drop_table('Products')
    # ### end Alembic commands ###
