"""uploading

Revision ID: 74a59d32523c
Revises: bf115cd927dd
Create Date: 2019-03-28 15:16:01.865647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74a59d32523c'
down_revision = 'bf115cd927dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('file_filename', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Products', 'file_filename')
    # ### end Alembic commands ###
