"""rm unique

Revision ID: 9b2c2407ae90
Revises: 457f403641e6
Create Date: 2019-03-22 23:28:01.786512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b2c2407ae90'
down_revision = '457f403641e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Layanan_slug_key', 'Layanan', type_='unique')
    op.drop_constraint('Layanan_title_key', 'Layanan', type_='unique')
    op.drop_constraint('Products_slug_key', 'Products', type_='unique')
    op.drop_constraint('Products_title_key', 'Products', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Products_title_key', 'Products', ['title'])
    op.create_unique_constraint('Products_slug_key', 'Products', ['slug'])
    op.create_unique_constraint('Layanan_title_key', 'Layanan', ['title'])
    op.create_unique_constraint('Layanan_slug_key', 'Layanan', ['slug'])
    # ### end Alembic commands ###
