"""back to unique

Revision ID: a32c0978b43b
Revises: 9b2c2407ae90
Create Date: 2019-03-22 23:41:53.437160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32c0978b43b'
down_revision = '9b2c2407ae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Layanan', ['slug'])
    op.create_unique_constraint(None, 'Layanan', ['title'])
    op.create_unique_constraint(None, 'Products', ['slug'])
    op.create_unique_constraint(None, 'Products', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Products', type_='unique')
    op.drop_constraint(None, 'Products', type_='unique')
    op.drop_constraint(None, 'Layanan', type_='unique')
    op.drop_constraint(None, 'Layanan', type_='unique')
    # ### end Alembic commands ###
