"""insert row r role"


Revision ID: b999a83e6914
Revises: 3b619fd16b25
Create Date: 2019-03-26 00:12:28.251598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b999a83e6914'
down_revision = '3b619fd16b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('kategori', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'kategori', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'kategori', type_='foreignkey')
    op.drop_column('kategori', 'role_id')
    op.drop_table('roles')
    # ### end Alembic commands ###
