"""ilangin filename_images di user

Revision ID: bf115cd927dd
Revises: ccbf8c951392
Create Date: 2019-03-27 23:13:12.533526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf115cd927dd'
down_revision = 'ccbf8c951392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_filename_images_key', 'user', type_='unique')
    op.drop_column('user', 'filename_images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('filename_images', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_filename_images_key', 'user', ['filename_images'])
    # ### end Alembic commands ###
