"""add relasi

Revision ID: ff29cc33e216
Revises: b999a83e6914
Create Date: 2019-03-26 00:28:36.517415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff29cc33e216'
down_revision = 'b999a83e6914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('kategori_role_id_fkey', 'kategori', type_='foreignkey')
    op.drop_column('kategori', 'role_id')
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.add_column('kategori', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('kategori_role_id_fkey', 'kategori', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
